config/routes.rb
Rails.application.routes.draw do

  root  'projects#index'

  resources :password_resets, only: [:create, :edit, :update]
  resources :user_sessions
  resources :users
  resources :projects, only: [:index, :show, :new, :create, :edit] do
    resources :rewards
    resources :pledges
  end

  get 'login' => 'user_sessions#new', :as => :login
  post 'logout' => 'user_sessions#destroy', :as => :logout

end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!

  has_many :projects
  has_many :pledges
  has_many :rewards, through: :pledges

  validates :password, length: { minimum: 3 }, if: -> { new_record? || changes[:crypted_password] }
  validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }

  validates :email, uniqueness: true
  validates :first_name, :last_name, :address, :city, :postal_code, presence:  true
  validates :phone_number, length: { is:  10 }
  validates :postal_code, length: { is: 6 }
  validates_inclusion_of :province, in: %w(AB BC SK MB ON QC NB NS PE NL NT YT NU)
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      auto_login(@user)
      redirect_to projects_url, notice: "Successfully signed up!"
    else
      render "new"
    end
  end

  def show
    @user = User.find(current_user)
  end

  def edit
    @user = User.find(current_user)
  end

  def update
    @user = User.find(current_user)
    if @user.update_attributes(user_params)
      redirect_to user_url(current_user)
    else
      render :new
    end
  end

  private
  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :first_name, :last_name,
                                 :address, :city, :province, :postal_code, :phone_number)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<h1>Create Your Profile:</h1>

<div class="container">
    <%= form_for @user do |f| %>
    <% if @user.errors.any? %>

    <div class="flash-error">
      <span>
        <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>
        <ul>
          <% @user.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
    <% end %>
        </span>
        </ul>
    </div>

  <div class="create-user-form">
    <aside>
          <%= f.label :email %><br />
    </aside>
    <article>
          <%= f.email_field :email %>
    </article>
    <aside>
          <%= f.label :password %><br />
    </aside>
    <article>
          <%= f.password_field :password %>
    </article>
    <aside>
          <%= f.label :password_confirmation %><br />
    </aside>
    <article>
          <%= f.password_field :password_confirmation %>
    </article>
    <aside>
          <%= f.label :first_name %><br />
    </aside>
    <article>
          <%= f.text_field :first_name %><br />
    </article>
    <aside>
        <%= f.label :last_name %><br />
    </aside>
    <article>
        <%= f.text_field :last_name %>
    </article>
    <aside>
        <%= f.label :phone_number  %><br />
    </aside>
    <article>
        <%= f.number_field :phone_number %>
    </article>
    <aside>
        <%= f.label :address  %><br />
    </aside>
    <article>
        <%= f.text_field :address %>
    </article>
    <aside>
        <%= f.label :city %><br />
    </aside>
    <article>
        <%= f.text_field :city %>
    </article>
    <aside>
        <%= f.label :province %><br />
    </aside>
    <article>
        <%= f.select :province, options_for_select("British Columbia":"BC", "Alberta":"AB", "Saskatchewan":"SK",
                                                   "Manitoba":"MB", "Ontario":"ON", "Quebec":"QC", "New Brunswick":"NB",
                                                   "Newfoundland":"NL", "Nova Scotia":"NS", "Prince Edward Island":"PE",
                                                   "Northwest Territories":"NT", "Yukon":"YT", "Nunavut":"NU") %>
    </article>
    <aside>
        <%= f.label :postal_code %> (ex. "M4K2E5") <br />
    </aside>
    <article>
        <%= f.text_field :postal_code %>
    </article>
    <aside>
        <%= f.submit %>
    </aside>
      <% end %>
    </aside>
</div>

app/views/users/edit.html.erb
<h1> Edit user </h1>

<%= render 'form' %>

<%= link_to "back", request.referer.present? ? request.referer : user_path(current_user) %>

app/views/users/new.html.erb
  <%= render 'form' %>

app/views/users/show.html.erb
<div id="profile-page">
  <div class="container">
    <h1 style="text-align: center; margin-bottom: 4rem">Profile</h1>
    <div class="row">
      <div class="col s6">
      <h1 class="profile-page-heading">Contact Information</h1>
        <p>
          Email Address: <%= @user.email %>
        </p>
        <p>
          First Name:  <%= @user.first_name %>
        </p>
        <p>
          Last Name:  <%= @user.last_name %>
        </p>
        <p>
          Address:  <%= @user.address %>
        </p>
        <p>
          City:  <%= @user.city %>
        </p>
        <p>
          Province:  <%= @user.province %>
        </p>
        <p>
          Postal Code:  <%= @user.postal_code %>
        </p>
        <p>
          Telephone Number:  <%= number_to_phone(@user.phone_number, area_code: true) %>
        </p>
        <p><%= link_to "Edit Profile", edit_user_path(current_user.id) %></p>

      </div>
        <div class="col s6">
          <% if @user.projects.any? %>
            <h1 class="profile-page-heading">Projects Owned</h1>

            <% @user.projects.each do |p| %>
              <div>
                <p>Project Title:  <%= p.title %><br/></p>
                <p>Project Description:  <%= p.short_description %></p>
              </div>
            <% end %>
          <% end %>
        </div>

        <div class="col s12">
          <h1 class="profile-page-heading">Backed Projects</h1>
            <% if @user.rewards.any? %>

            <% @user.rewards.each do |r| %>

                title:  <%= r.title %><br/>
                description:  <%= r.description %><br/>

            <% end %>
          <% end %>
        </div>
    </div>
  </div>
</div>