config/routes.rb
Rails.application.routes.draw do

  root  'projects#index'

  resources :password_resets, only: [:create, :edit, :update]
  resources :user_sessions
  resources :users
  resources :projects, only: [:index, :show, :new, :create, :edit] do
    resources :rewards
    resources :pledges
  end

  get 'login' => 'user_sessions#new', :as => :login
  post 'logout' => 'user_sessions#destroy', :as => :logout

end

app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :user
  belongs_to :category
  has_many :rewards
  has_many :pledges, through: :rewards

  validates :title, :short_description, :long_description, :risk_description, presence: true
  validates_associated :category, :user
  validates :funding_amount, :numericality => { :greater_than => 0 }
  validate :end_date_is_after_start_date

  accepts_nested_attributes_for :rewards, reject_if: :all_blank

  mount_uploader :image, ImageUploader

  validates_processing_of :image
  validate :image_size_validation

  def count_backers
    return self.pledges.count
  end

  def amount_pledged
    return self.pledges.sum(:amount).to_f
  end

  def ended?
    return DateTime.now.to_date > self.end_date
  end

  def days_remaining
    return (self.end_date.beginning_of_day.to_date - self.created_at.beginning_of_day.to_date).to_i
  end

  def owner_name
    return "#{self.user.first_name} #{self.user.last_name}"
  end

  def funded?
    return self.amount_pledged > self.funding_amount
  end

  private

  def end_date_is_after_start_date
    return false if self.end_date.blank?

    if self.end_date < DateTime.now
      errors.add(:end_date, "end date cannot be before the start date")
    end
  end

  def image_size_validation
    errors[:image] << "should be less than 500KB" if image.size > 0.5.megabytes
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  def index
    @projects = if params[:search]
      Project.where("LOWER(title) LIKE LOWER(?)", "%#{params[:search]}%")
    else
      Project.all
    end

    respond_to do |format|
      format.html
      format.js
    end
  end

  def show
    @project = Project.find(params[:id])
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)
    @project.user = current_user

    if @project.save
      @project.image.url # => '/url/to/file.png'
      @project.image.current_path # => 'path/to/file.png'
      @project.image_identifier # => 'file.png'
      redirect_to projects_url
     else
      render :new
    end
  end

  def edit
  end

  private
  def project_params
    params.require(:project).permit(:title, :short_description, :long_description, :risk_description,
                                    :start_date, :end_date, :created_at, :updated_at, :category_id,
                                    :funding_amount, :user_id, :image, rewards_attributes: [:title, :amount, :description])
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_for @project do |f| %>
  <% if @project.errors.any? %>
    <div id="flash-error">
      <span>
        <h2><%= pluralize(@project.errors.count, "error") %> prohibited this user from being saved:</h2>
        <ul>
        <% @project.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </span>
    </div>
  <% end %>


<div class="choose-category">
  <h1>What Type of Project Would You Like to Create?</h1>
  <div id="category-picker">
    <%= select_tag :category_id, options_for_select(Category.all.collect {|c| [ c.description, c.id ] }) %>
  </div>
</div>

<div class="container">

  <table class="create-project-table">
    <tr>
      <td><%= f.label :title %></td>
      <td><%= f.text_field :title %></td>
    </tr>

    <tr>
      <td><%= f.label :short_description %></td>
      <td><%= f.text_field :short_description%></td>

    </tr>

    <tr>
      <td><%= f.label :long_description %></td>
      <td><%= f.text_area :long_description %></td>

    </tr>

    <tr>
      <td><%= f.label :risk_description %></td>
      <td><%= f.telephone_field :risk_description %></td>

    </tr>

    <tr>
      <td><%= f.label :end_date %></td>
      <td><%= f.date_field :end_date %></td>

    </tr>

    <tr>
      <td><%= f.label :funding_amount %></td>
      <td><%= f.number_field :funding_amount %></td>
    </tr>
    <tr>
      <td><%= f.label :image %></td>
      <td><%= f.file_field :image %></td>
    </tr>

    <tr>
      <%= f.fields_for :rewards, [Reward.new, Reward.new, Reward.new] do |reward| %>
      <td><%= reward.label :Reward_title %></td>
      <td><%= reward.text_field :title %>  </td>
    </tr>

    <tr>
      <td><%= reward.label :Reward_description %></td>
      <td><%= reward.text_area :description %></td>
    </tr>

    <tr>
      <td><%= reward.label :Reward_amount %></td>
      <td><%= reward.number_field :amount %></td>
    </tr>

    <% end %>
  </table>
  <div class="actions" style="text-align: center">
    <%= f.submit %>
  </div>
  <% end %>
</div>

app/views/projects/_project.html.erb
  <% @projects.each do |project| %>
    <!-- <table id="project-index-table">
      <tr>
        <td id="index-project-name-desc"><p><%= link_to project.title, project_path(project.id) %></p>
          <p><%= project.short_description %></p></td>
        <td id="project-img"><img src="<%= project.image %>"></td>
    </table> -->

<div class="row">
  <div class="col s4 push-s8">
    <img src="<%= project.image %>">
  </div>
  <div class="col s8 pull-s4">
    <%= link_to project.title, project_path(project.id), id: "browse-project-title" %>
  </div>
</div>

<% end %>

app/views/projects/edit.html.erb
<h1>Projects#edit</h1>
<p>Find me in app/views/projects/edit.html.erb</p>

app/views/projects/index.html.erb
<!-- HERO IMAGE -->

<div class="hero">
  <div class="hero-content">
    <h2>Bring your dream project to life.  </h2>
  </div>
</div>

<!-- HERO END -->

<div class="row">
  <div class="col s6 m4">
    <div class="card">
      <div class="card-image">
        <img src="http://www.pei.com/wp-content/uploads/2010/03/project-manager-roll.jpg">
        <span class="card-title">Join, browse and create!</span>
      </div>
      <div class="card-content">
        <p>What project or idea have you been waiting to finally get off the ground? After you've registered with Crowdfundr, create a project that other users can view and pledge to. Or browse and contribute to other users' projects! </p>
      </div>
      <div class="card-action">
        <%= link_to "Sign up!", new_user_path %>
      </div>
    </div>
  </div>

  <div class="col s6 m4">
    <div class="card">
      <div class="card-image">
        <%= image_tag("mystery-box.png") %>
        <span class="card-title">Pledge to projects. Receive rewards.</span>
      </div>
      <div class="card-content">
        <p>If you see any projects on here that you like, pledge a contribution of your choosing and get rewards from the project owner! Rewards can include an exclusive pre-order discount rate, bonus bundles, and personalized gifts from the project owner. </p>
      </div>
      <div class="card-action">
        <!-- <a href="#">This is a link</a> -->
      </div>
    </div>
  </div>

  <div class="col s12 m4">
    <div class="card">
      <div class="card-image">
<%=         image_tag("crowdfundr-funding.png")%>
            <span class="card-title"> Get your project funded!</span>
      </div>
      <div class="card-content">
        <p>With help from other Crowdfundrs, get your project, product, or business rolling! Start as many projects and participate in as many campaigns as you like.</p>
      </div>
      <div class="card-action">
        <a href="#">This is a link</a>
      </div>
    </div>
  </div>

</div>

<div class="container">
  <!-- <h1 id="index-current-projects">Here's a List of Our Current Projects:</h1> -->

  <div id="search-bar">
    <%= form_tag projects_path, method: :get, authentication: false, id: 'search-form', role: "search" do %>
      <%= text_field_tag :search, params[:search] %>
      <button type="submit">Search</button>
    <% end %>
  </div>

  <!-- SEARCHBAR -->

  <!-- CURRENT PROJECTS -->
  <div id="projects">
    <%= render @projects %>
  </div>
</div>
<!-- CURRENT PROJECTS -->

app/views/projects/index.js.erb
$('#projects').html("<%= escape_javascript(render @projects) %>");

app/views/projects/new.html.erb
<%= render 'form' %>

app/views/projects/show.html.erb
<%= link_to "Back to All Projects", request.referer.present? ? request.referer : root_path, class: "waves-effect waves-teal btn-flat", id: "back-to-all-projects-btn" %>

<div class="container">

  <div class="title-and-creator">
    <h1><%= @project.title %></h1>
    <h4>by: <%= @project.owner_name %></h4>
    <p></b> <%= @project.short_description %></p>
  </div>

  <div class="main-project-info">
    <table class="main-project-table">
      <tr class="main-project-table-row">

        <td class="column-one">
          <div class="video">
            <div class="video-wrapper">
            <!-- <iframe width="560" height="315" src="https://www.youtube.com/embed/gKUI--Tycg8?list=FL-nhrSdZC6vefG4VmW5NR8Q" frameborder="0" allowfullscreen></iframe> -->
            <%= image_tag @project.image %>
            </div>
          </div>
        </td>

        <td class="column-two">
        <table class="project-stats">
          <tr>
        <td id="backers">
          <p>Number of Backers: <%= @project.count_backers %></p>
        </td>
        </tr>
        <tr>
            <td id="pledged">
          <p>Amount Pledged: <%= number_to_currency(@project.amount_pledged) %></p>
        </td>
      </tr>
      <tr>
        <td id="days-to-go">
          <p>Days To Go: <%= @project.days_remaining %></p>
        </td>
      </tr>
      <tr>
          <td id="back-this-project">
          <% if current_user %>
            <button class="back-this-project-btn">
              <%= button_to "Back this Project", new_project_pledge_path(@project), method: :get %>
            </button>
            <% else %>
            <p>
              Please register or login to back this project.
            </p>
            <% end %>
          </td>
        </tr>
      </td>
    </table>
  </table>
</div>
    <div class="short-description">
      <h2><%= @project.short_description %></h2>
    </div>

  <div class="long-description">
    <h3><%= @project.long_description %></h3>
  </div>

  <div class="show-rewards">
  <% @project.rewards.each do |r| %>
  <div>
    <div id="reward-title"><%= r.title %><br/></div>
    <%= r.description %><br/>
    <%= number_to_currency(r.amount) %><br/>
  </div>
    <% if current_user %>
      <%= button_to "Back this Project", new_project_pledge_path(@project), method: :get %>
    <% else %>
      <p>Register or Login to Back This Project!</p>
    <% end %>
  <% end %>
  </div>

    </div>
  </div>
</div>