config/routes.rb
Rails.application.routes.draw do

  root  'projects#index'

  resources :password_resets, only: [:create, :edit, :update]
  resources :user_sessions
  resources :users
  resources :projects, only: [:index, :show, :new, :create, :edit] do
    resources :rewards
    resources :pledges
  end

  get 'login' => 'user_sessions#new', :as => :login
  post 'logout' => 'user_sessions#destroy', :as => :logout

end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    if @user = login(params[:email], params[:password])
      redirect_back_or_to root_url, notice: "You're logged in."
    else
      flash.now[:alert] = "Invalid email or password"
      render action: "new"
    end
  end

  def destroy
    logout
    redirect_to root_url, notice: "Logged out."
  end
end

app/views/user_sessions/_forgot_password_form.html.erb
<%= form_tag password_resets_path, :method => :post do %>
  <aside>
    Enter your email address below:<br />
  </aside>

  <article>
    <%= text_field_tag :email %> <%= submit_tag "Reset My Password!" %>
  </article>
<% end %>

app/views/user_sessions/new.html.erb
<div class="container new-session-form">

  <h1>Log in</h1>
  <%= form_tag user_sessions_path, method: :post do %>

    <aside>
      Email Address:
    </aside>

    <article>
      <%= text_field_tag :email, params[:email] %>
    </article>

    <aside>
      Password:
    </aside>

    <article>
      <%= password_field_tag :password %>
    </article>

    <aside>
      <%= submit_tag "Log in" %>
    </aside>
  <% end %>
</div>

<div class="container forgot-password-form">
  <h2>Forgot Password?</h2>
  <%= render 'forgot_password_form' %>
</div>