config/routes.rb
Rails.application.routes.draw do

  root  'projects#index'

  resources :password_resets, only: [:create, :edit, :update]
  resources :user_sessions
  resources :users
  resources :projects, only: [:index, :show, :new, :create, :edit] do
    resources :rewards
    resources :pledges
  end

  get 'login' => 'user_sessions#new', :as => :login
  post 'logout' => 'user_sessions#destroy', :as => :logout

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CrowdFundr</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

</head>
<body>

<!-- NAVIGATION -->
  <!-- <header class="centered-navigation" role="banner">
  <div class="centered-navigation-wrapper">
    <a href="javascript:void(0)" class="mobile-logo">
      <%= image_tag("cf-footer") %>
    </a>
    <a href="javascript:void(0)" id="js-centered-navigation-mobile-menu" class="centered-navigation-mobile-menu">MENU</a>
    <nav role="navigation">
      <ul id="js-centered-navigation-menu" class="centered-navigation-menu show">

        <% if current_user%>
          <li class="nav-link"><a><%= link_to "Create a Project", new_project_path %> </a></li>
        <% end %>
        <li class="nav-link logo" style="margin: auto">
          <a href="<%= projects_path %>" class="logo">
            <%= image_tag("crowdfundr-logo.png") %>
          </a>
        </li>
        <% if current_user %>

        <li id="js-centered-more" class="nav-link more"><a href="javascript:void(0)">Hi, <%= current_user.email %>!</a>
          <ul class="submenu">
            <li><a href="<%= user_path(current_user.id) %>">My Profile</a></li>
            <li><%= link_to "Logout", :logout, method: :post %></li>
          </ul>

        </li>
        <% else %>
        <li class="nav-link"><a><%= link_to "Register", new_user_path %></a></li>
        <li class="nav-link"><a><%= link_to "Login", :login %></a></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header> -->

<!-- Nav Dropdown Menu -->

<% if current_user %>
<ul id="dropdown1" class="dropdown-content">
  <li><a href="<%= user_path(current_user.id) %>">Profile</a></li>
  <li><a href="#">Projects</a></li>
  <li class="divider"></li>
  <li><%= link_to "Logout", :logout, method: :post %></li>
</ul>
<% end %>

<!-- Nav -->

<nav>
  <div class="nav-wrapper">
    <a href="/" class="brand-logo">Crowdfundr</a>

    <ul class="right hide-on-med-and-down">
      <% if current_user %>

      <li><a id="browse-projects-link" href="">Browse Projects</a></li>
        <li><%= link_to "Create a Project", new_project_path %></li>
        <!-- Dropdown Trigger -->
        <li><a class="dropdown-button" href="#!" data-activates="dropdown1">Hi, <%= current_user.first_name %>!<i class="material-icons right">arrow_drop_down</i></a></li>

      <% else %>
        <li><a href="#">Browse Projects</a></li>
        <li><%= link_to "Register", new_user_path %></li>
        <li><%= link_to "Log In", :login %></li>
      <% end %>

    </ul>
  </div>
</nav>

  <% if notice %>
    <p class="alert alert-success"><%= notice %></p>
  <% end %>
  <% if alert %>
    <p class="alert alert-danger"><%= alert %></p>
  <% end %>

<%= yield %>

<footer class="footer" role="contentinfo">
  <div class="footer-logo">
    <%= image_tag("cf-footer") %>
  </div>
  <div class="footer-links">
    <ul>
      <li><h3>Content</h3></li>
      <li><a href="javascript:void(0)">About</a></li>
      <li><a href="javascript:void(0)">Contact</a></li>
      <li><a href="javascript:void(0)">Products</a></li>
    </ul>
    <ul>
      <li><h3>Follow Us</h3></li>
      <li><a href="javascript:void(0)">Facebook</a></li>
      <li><a href="javascript:void(0)">Twitter</a></li>
      <li><a href="javascript:void(0)">YouTube</a></li>
    </ul>
    <ul>
      <li><h3>Legal</h3></li>
      <li><a href="javascript:void(0)">Terms and Conditions</a></li>
      <li><a href="javascript:void(0)">Privacy Policy</a></li>
    </ul>
  </div>

<hr>

  <p>This app was built by Mike Thai, Arnold Redoblado, and Amin Shaifee</p>
</footer>
<script src="particles.js"></script>
</body>
</html>